name: Feature Request
description: Suggest a new feature or enhancement
labels: ["enhancement"]
body:
  - type: input
    id: version
    attributes:
      label: Version
      placeholder: e.g. 1.0.0-beta
    validations:
      required: true
  - type: textarea
    id: description
    attributes:
      label: Description
      description: What would you like to see added or changed?
    validations:
      required: true
  - type: textarea
    id: motivation
    attributes:
      label: Motivation
      description: Why would this be useful?
    validations:
      required: false
